// LEADS
export const GET_LEADS = "GET_LEADS"
export const SET_SELECTED_RECORDS = "SET_SELECTED_RECORDS"

// PAYMENTS
export const PAYMENTS_HISTORY_ON_SCREEN = "PAYMENTS_HISTORY_ON_SCREEN"
export const PAYMENTS_HISTORY_UPDATE = "PAYMENTS_HISTORY_UPDATE"
export const PAYMENTS_HISTORY_START = "PAYMENTS_HISTORY_START"
export const PAYMENTS_HISTORY_FINISH = "PAYMENTS_HISTORY_FINISH"

// NOTIFICATIONS
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION"

export const ACTION_WITHDRAW_ELEMENT_ON_SCREEN = "WITHDRAW_ELEMENT_ON_SCREEN"
export const ACTION_WITHDRAW_ELEMENT_START_LOADING =
  "ACTION_WITHDRAW_ELEMENT_START_LOADING"
export const ACTION_WITHDRAW_ELEMENT_FINISH_LOADING =
  "ACTION_WITHDRAW_ELEMENT_FINISH_LOADING"

// SIGNUP
export const SIGNUP_FORM_HANDLE_CHANGE = "SIGNUP_FORM_HANDLE_CHANGE"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
