export default {
  // APP
  TOGGLE_RESULTS_MODE: "TOGGLE_RESULTS_MODE",

  // LEADS
  BUY_LEADS_FETCH_LEADS: "BUY_LEADS_FETCH_LEADS",
  BUY_LEADS_FETCH_SUCCESS: "BUY_LEADS_FETCH_SUCCESS",
  BUY_LEADS_FETCH_ERROR: "BUY_LEADS_FETCH_ERROR",
  BUY_LEADS_SET_SELECTED_LEADS: "BUY_LEADS_SET_SELECTED_LEADS",

  SELL_LEADS_FETCH_LEADS: "SELL_LEADS_FETCH_LEADS",
  SELL_LEADS_FETCH_SUCCESS: "SELL_LEADS_FETCH_SUCCESS",
  SELL_LEADS_FETCH_ERROR: "SELL_LEADS_FETCH_ERROR",
  SELL_LEADS_SET_SELECTED_LEADS: "SELL_LEADS_SET_SELECTED_LEADS",

  MY_LEADS_FETCH_LEADS: "MY_LEADS_FETCH_LEADS",
  MY_LEADS_FETCH_SUCCESS: "MY_LEADS_FETCH_SUCCESS",
  MY_LEADS_FETCH_ERROR: "MY_LEADS_FETCH_ERROR",
  MY_LEADS_SET_SELECTED_LEADS: "MY_LEADS_SET_SELECTED_LEADS",

  CLEAR_ALL_LEADS: "CLEAR_ALL_LEADS",

  // MOVE TO SELL
  MY_LEADS_MOVE_TO_SELL_BEGIN: "MY_LEADS_MOVE_TO_SELL_BEGIN",
  MY_LEADS_MOVE_TO_SELL_SUCCESS: "MY_LEADS_MOVE_TO_SELL_SUCCESS",
  MY_LEADS_MOVE_TO_SELL_ERROR: "MY_LEADS_MOVE_TO_SELL_ERROR",

  // PAYMENTS
  PAYMENTS_HISTORY_LOADING_START: "PAYMENTS_HISTORY_LOADING_START",
  PAYMENTS_HISTORY_LOADING_END: "PAYMENTS_HISTORY_LOADING_END",
  PAYMENTS_HISTORY_UPDATE: "PAYMENTS_HISTORY_UPDATE",
  PAYMENTS_HISTORY_ERROR: "PAYMENTS_HISTORY_ERROR",
  PAYMENTS_HISTORY_EXPORT_PAYMENTS: "PAYMENTS_HISTORY_EXPORT_PAYMENTS",
  PAYMENTS_HISTORY_ON_SCROLL_BOTTOM: "PAYMENTS_HISTORY_ON_SCROLL_BOTTOM",

  // NOTIFICATIONS
  NOTIFICATION_SHOW: "NOTIFICATION_SHOW",
  NOTIFICATIONS_SHOW: "NOTIFICATIONS_SHOW",
  NOTIFICATIONS_HIDE: "NOTIFICATIONS_HIDE",
  NOTIFICATIONS_CLICK: "NOTIFICATIONS_CLICK",
  NOTIFICATIONS_UPDATE: "NOTIFICATIONS_UPDATE",
  NOTIFICATIONS_FETCH_START: "NOTIFICATIONS_FETCH_START",
  NOTIFICATIONS_FETCH_ERROR: "NOTIFICATIONS_FETCH_ERROR",
  NOTIFICATIONS_TABLE_LOADING_START: "NOTIFICATIONS_TABLE_LOADING_START",
  NOTIFICATIONS_TABLE_LOADING_END: "NOTIFICATIONS_TABLE_LOADING_END",
  NOTIFICATIONS_TABLE_UPDATE: "NOTIFICATIONS_TABLE_UPDATE",
  NOTIFICATIONS_TABLE_ERROR: "NOTIFICATIONS_TABLE_ERROR",

  // BALANCE
  BALANCE_UPDATE: "BALANCE_UPDATE",
  BALANCE_WIDGET_LOADING_START: "BALANCE_WIDGET_LOADING_START",
  BALANCE_WIDGET_LOADING_FINISH: "BALANCE_WIDGET_LOADING_FINISH",

  // SIGNUP
  SIGNUP_HANDLE_CHANGE: "SIGNUP_HANDLE_CHANGE",
  SIGNUP_SUBMIT: "SIGNUP_SUBMIT",
  SIGNUP_LOADING: "SIGNUP_LOADING",
  SIGNUP_FINISH: "SIGNUP_FINISH",
  SIGNUP_ERROR: "SIGNUP_ERROR",

  // COMPLETE REGISTRATION
  COMPLETE_REGISTRATION_HANDLE_CHANGE: "COMPLETE_REGISTRATION_HANDLE_CHANGE",
  COMPLETE_REGISTRATION_SUBMIT: "COMPLETE_REGISTRATION_SUBMIT",
  COMPLETE_REGISTRATION_LOADING: "COMPLETE_REGISTRATION_LOADING",
  COMPLETE_REGISTRATION_FINISH: "COMPLETE_REGISTRATION_FINISH",
  COMPLETE_REGISTRATION_ERROR: "COMPLETE_REGISTRATION_ERROR",

  // LOGIN
  LOGIN_HANDLE_CHANGE: "LOGIN_HANDLE_CHANGE",
  LOGIN_SUBMIT: "LOGIN_SUBMIT",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_FINISH: "LOGIN_FINISH",
  LOGIN_ERROR: "LOGIN_ERROR",

  // FORGOT_PASSWORD
  FORGOT_PASSWORD_HANDLE_CHANGE: "FORGOT_PASSWORD_HANDLE_CHANGE",
  FORGOT_PASSWORD_SUBMIT: "FORGOT_PASSWORD_SUBMIT",
  FORGOT_PASSWORD_LOADING: "FORGOT_PASSWORD_LOADING",
  FORGOT_PASSWORD_FINISH: "FORGOT_PASSWORD_FINISH",

  // EMAIL CONFIRMATION
  EMAIL_CONFIRMATION_RESEND: "EMAIL_CONFIRMATION_RESEND",
  EMAIL_CONFIRMATION_ERROR: "EMAIL_CONFIRMATION_ERROR",

  // USER SETTINGS
  USER_SETTINGS_HANDLE_CHANGE: "USER_SETTINGS_HANDLE_CHANGE",
  USER_SETTINGS_ERROR: "USER_SETTINGS_ERROR",
  USER_SETTINGS_CLEAR: "USER_SETTINGS_CLEAR",
  USER_SETTINGS_SUBMIT: "USER_SETTINGS_SUBMIT",
  USER_SETTINGS_LOADING: "USER_SETTINGS_LOADING",
  USER_SETTINGS_FINISH: "USER_SETTINGS_FINISH",

  // CSV UPLOAD
  CSV_UPLOAD_LOADING_DONE: "CSV_UPLOAD_LOADING_DONE",
  CSV_UPLOAD_LOADING_CHANGE: "CSV_UPLOAD_LOADING_CHANGE",
  CSV_UPLOAD_PICK_FILE: "CSV_UPLOAD_PICK_FILE",
  CSV_UPLOAD_SUCCESS: "CSV_UPLOAD_SUCCESS",
  CSV_UPLOAD_ERROR: "CSV_UPLOAD_ERROR",
  CSV_UPLOAD_SUBMIT: "CSV_UPLOAD_SUBMIT",

  // ADD LEAD
  ADD_LEAD_AGREE_TO_TERMS: "ADD_LEAD_AGREE_TO_TERMS",
  ADD_LEAD_CLEAR_FORM: "ADD_LEAD_CLEAR_FORM",
  ADD_LEAD_SUBMIT_FORM: "ADD_LEAD_SUBMIT_FORM",
  ADD_LEAD_SUBMIT_SUCCESS: "ADD_LEAD_SUBMIT_SUCCESS",
  ADD_LEAD_GET_DB_FIELDS: "ADD_LEAD_GET_DB_FIELDS",
  ADD_LEAD_HANDLE_FORM_CHANGE: "ADD_LEAD_HANDLE_FORM_CHANGE",
  ADD_LEAD_FORM_ERROR: "ADD_LEAD_FORM_ERROR",
  ADD_LEAD_LOADING_START: "ADD_LEAD_LOADING_START",
  ADD_LEAD_LOADING_END: "ADD_LEAD_LOADING_END",

  // CSV MAPPING
  CSV_MAPPING_FORM_HANDLE_CHANGE: "CSV_MAPPING_FORM_HANDLE_CHANGE",
  CSV_MAPPING_MAP_HANDLE_CHANGE: "CSV_MAPPING_MAP_HANDLE_CHANGE",
  CSV_MAPPING_ERROR: "CSV_MAPPING_ERROR",
  CSV_MAPPING_CLEAR_FORM: "CSV_MAPPING_CLEAR_FORM",
  CSV_MAPPING_SUBMIT: "CSV_MAPPING_SUBMIT",
  CSV_MAPPING_GET_DB_FIELDS: "CSV_MAPPING_GET_DB_FIELDS",
  CSV_MAPPING_GET_FILE_FIELDS: "CSV_MAPPING_GET_FILE_FIELDS",
  CSV_MAPPING_FORM_ERROR: "CSV_MAPPING_FORM_ERROR",
  CSV_MAPPING_AGREE_TO_TERMS: "CSV_MAPPING_AGREE_TO_TERMS",

  // USER MENU
  USER_MENU_OPEN: "USER_MENU_OPEN",
  USER_MENU_CLOSE: "USER_MENU_CLOSE",
  USER_MENU_CLICK: "USER_MENU_CLICK",

  // USER
  LOG_IN: "LOG_IN",
  LOGGED_IN: "LOGGED_IN",
  LOG_OUT: "LOG_OUT",
  LOGGED_OUT: "LOGGED_OUT",

  // CHECKOUT
  CHECKOUT_BUY_START: "CHECKOUT_BUY_START",
  CHECKOUT_BUY_SUCCESS: "CHECKOUT_BUY_SUCCESS",
  CHECKOUT_BUY_ERROR: "CHECKOUT_BUY_ERROR",

  // DISPUTE
  DISPUTE_HANDLE_CHANGE: "DISPUTE_HANDLE_CHANGE",
  DISPUTE_SUBMIT: "DISPUTE_SUBMIT",
  DISPUTE_LOADING: "DISPUTE_LOADING",
  DISPUTE_FINISH: "DISPUTE_FINISH",
  DISPUTE_ERROR: "DISPUTE_ERROR",

  // LANGUAGE SELECTOR
  LANGUAGE_SELECTOR_UPDATE: "LANGUAGE_SELECTOR_UPDATE",
  LANGUAGE_SELECTOR_CLICK: "LANGUAGE_SELECTOR_CLICK",
  LANGUAGE_SELECTOR_OPEN: "LANGUAGE_SELECTOR_OPEN",
  LANGUAGE_SELECTOR_CLOSE: "LANGUAGE_SELECTOR_CLOSE",

  // ROUTE
  GOTO_DEFAULT_HOME: "GOTO_DEFAULT_HOME",
  FETCH_USER_AGAIN: "FETCH_USER_AGAIN",
  REDIRECT_IF_NEEDED: "REDIRECT_IF_NEEDED",

  //WITHDRAW PAGE
  WITHDRAW_PAGE_FORM_UPDATE: "WITHDRAW_PAGE_FORM_UPDATE",
  WITHDRAW_PAGE_SUBMIT: "WITHDRAW_PAGE_SUBMIT",
  WITHDRAW_PAGE_LOADING_START: "WITHDRAW_PAGE_LOADING_START",
  WITHDRAW_PAGE_LOADING_FINISH: "WITHDRAW_PAGE_LOADING_FINISH",
  WITHDRAW_PAGE_ERROR: "WITHDRAW_PAGE_ERROR",
}
