import types from "../actions/types"

const initialState = [
  {
    key: "date",
    name: "date",
    sortable: true,
    editable: false,
    maxWidth: "80px",
    minWidth: "80px",
  },
  {
    key: "name",
    name: "name",
    sortable: true,
    editable: false,
    maxWidth: "90px",
    minWidth: "90px",
    private: true,
  },
  {
    key: "telephone",
    name: "telephone",
    sortable: true,
    editable: false,
    maxWidth: "auto",
    minWidth: "auto",
    private: true,
  },
  {
    key: "email",
    name: "email",
    sortable: true,
    editable: false,
    maxWidth: "auto",
    minWidth: "auto",
    private: true,
  },
  {
    key: "state",
    name: "state",
    sortable: true,
    editable: false,
    maxWidth: "80px",
    minWidth: "80px",
  },
  {
    key: "city",
    name: "city",
    sortable: true,
    editable: false,
    maxWidth: "70px",
    minWidth: "70px",
  },
  {
    key: "property_type",
    name: "property type",
    sortable: true,
    editable: false,
    maxWidth: "auto",
    minWidth: "auto",
  },
  {
    key: "size",
    name: "size (SqFt)",
    sortable: true,
    editable: false,
    maxWidth: "50px",
    minWidth: "50px",
  },
  {
    key: "budget",
    name: "budget",
    sortable: true,
    editable: false,
    maxWidth: "70px",
    minWidth: "70px",
  },
  {
    key: "bedrooms",
    name: "rooms",
    sortable: true,
    editable: false,
    maxWidth: "80px",
    minWidth: "80px",
  },
  {
    key: "floor",
    name: "floor",
    sortable: true,
    editable: false,
    maxWidth: "50px",
    minWidth: "50px",
  },
  {
    key: "specification",
    name: "specification",
    sortable: true,
    editable: false,
    maxWidth: "auto",
    minWidth: "auto",
  },
  {
    key: "lead_price",
    name: "lead price",
    sortable: true,
    editable: false,
    maxWidth: "auto",
    minWidth: "auto",
  },
  {
    key: "status",
    name: "status",
    sortable: true,
    editable: false,
    maxWidth: "65px",
    minWidth: "65px",
    private: true,
  },
]

const fields = (state = initialState, action) => {
  return state
}

export default fields
