const fields = [
  {
    key: "date",
    name: "Date Published",
    sortable: true,
    editable: false,
    maxWidth: "80px",
    minWidth: "80px",
  },
  {
    key: "Description",
    name: "Description",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
  },
  {
    key: "Bedrooms/Baths",
    name: "Bedrooms / Baths",
    sortable: true,
    editable: true,
    maxWidth: "80px",
    minWidth: "80px",
  },
  {
    key: "Type",
    name: "Type",
    sortable: true,
    editable: true,
    maxWidth: "90px",
    minWidth: "90px",
  },
  {
    key: "Price",
    name: "Price",
    sortable: true,
    editable: true,
    maxWidth: "70px",
    minWidth: "70px",
  },
  {
    key: "Size",
    name: "Size (SqFt)",
    sortable: true,
    editable: true,
    maxWidth: "50px",
    minWidth: "50px",
  },
  {
    key: "State",
    name: "State",
    sortable: true,
    editable: true,
    maxWidth: "80px",
    minWidth: "80px",
  },
  {
    key: "Location",
    name: "Location",
    sortable: true,
    editable: true,
    maxWidth: "70px",
    minWidth: "70px",
  },
  {
    key: "Housing Type",
    name: "Housing Type",
    sortable: true,
    editable: true,
    maxWidth: "130px",
    minWidth: "130px",
  },
  {
    key: "Contact Person",
    name: "Contact Person",
    sortable: true,
    editable: true,
    maxWidth: "90px",
    minWidth: "90px",
    private: true,
  },
  {
    key: "Telephone",
    name: "Telephone",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    private: true,
  },
  {
    key: "lead_price",
    name: "Lead Price",
    sortable: true,
    editable: true,
    maxWidth: "100px",
    minWidth: "100px",
  },
]

export default fields
