import LANGUAGES from "./langs"

const OPTIONS = {
  YES_OR_NO: [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }],
  FUNCTIONALITY: [
    { type: "functionality", value: "personal", label: "Personal" },
    { type: "functionality", value: "corporate", label: "Corporate" },
    { type: "functionality", value: "educational", label: "Educational" },
    { type: "functionality", value: "portfolio", label: "Portfolio" },
    { type: "functionality", value: "restaurant", label: "Restaurant" },
    { type: "functionality", value: "other", label: "Other" },
    {
      type: "functionality",
      value: "samall business",
      label: "Small Business",
    },
    { type: "functionality", value: "personal", label: "Portfolio" },
  ],
  CONTENT_UPDATES: [
    { value: "Mostly Static", label: "Mostly Static" },
    { value: "Dynamic", label: "Dynamic" },
  ],
  LANGUAGES: LANGUAGES,
}

const fields = [
  {
    key: "industry",
    name: "Industry",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "date",
    name: "Date Published",
    sortable: true,
    editable: false,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "pages",
    name: "Number of pages",
    sortable: true,
    editable: true,
    maxWidth: "100px",
    minWidth: "100px",
    type: "input",
    options: [],
  },
  {
    key: "content_updates",
    name: "Content updates",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "100px",
    type: "select",
    options: OPTIONS.CONTENT_UPDATES,
  },
  {
    key: "functionality",
    name: "Functionality",
    sortable: true,
    editable: true,
    maxWidth: "100px",
    minWidth: "100px",
    type: "multiselect",
    options: OPTIONS.FUNCTIONALITY,
  },
  {
    key: "mobile_design",
    name: "Mobile design",
    sortable: true,
    editable: true,
    maxWidth: "75px",
    minWidth: "75px",
    type: "select",
    options: OPTIONS.YES_OR_NO,
  },
  {
    key: "seo",
    name: "SEO",
    sortable: true,
    editable: true,
    maxWidth: "50px",
    minWidth: "50px",
    type: "select",
    options: OPTIONS.YES_OR_NO,
  },
  {
    key: "content_management",
    name: "Content Management",
    sortable: true,
    editable: true,
    maxWidth: "50px",
    minWidth: "50px",
    type: "select",
    options: OPTIONS.YES_OR_NO,
  },
  {
    key: "e_commerce",
    name: "E-commerce",
    sortable: true,
    editable: true,
    maxWidth: "100px",
    minWidth: "100px",
    type: "select",
    options: OPTIONS.YES_OR_NO,
  },
  {
    key: "blog",
    name: "Blog",
    sortable: true,
    editable: true,
    maxWidth: "50px",
    minWidth: "50px",
    type: "select",
    options: OPTIONS.YES_OR_NO,
  },
  {
    key: "budget",
    name: "Budget",
    sortable: true,
    editable: true,
    maxWidth: "85px",
    minWidth: "85px",
    type: "input",
  },
  {
    key: "languages",
    name: "Languages",
    sortable: true,
    editable: true,
    maxWidth: "80px",
    minWidth: "80px",
    type: "multiselect",
    options: OPTIONS.LANGUAGES,
  },
  {
    key: "hosting",
    name: "Hosting",
    sortable: true,
    editable: true,
    maxWidth: "65px",
    minWidth: "65px",
    type: "select",
    options: OPTIONS.YES_OR_NO,
  },
  {
    key: "comments",
    name: "Comments",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "contact_person",
    name: "Contact Person",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    private: true,
    options: [],
  },
  {
    key: "email",
    name: "Email",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    private: true,
    options: [],
  },
  {
    key: "telephone",
    name: "Telephone",
    sortable: true,
    editable: true,
    maxWidth: "80px",
    minWidth: "80px",
    type: "input",
    private: true,
    options: [],
  },
  {
    key: "lead_price",
    name: "Lead Price",
    sortable: true,
    editable: true,
    maxWidth: "100px",
    minWidth: "100px",
    type: "input",
    options: [],
  },
]

export default fields
