const fields = [
  {
    key: "Industry",
    name: "Industry",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "Category",
    name: "Category",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "date",
    name: "Date Published",
    sortable: true,
    editable: false,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "Pages",
    name: "Pages",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "Content updates",
    name: "Content updates",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["Mostly Static", "Dynamic"],
  },
  {
    key: "Functionality",
    name: "Functionality",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: [
      "Personal",
      "Corporate",
      "Educational",
      "Portfolio",
      "Restaurant",
      "Small Business",
      "Other",
    ],
  },
  {
    key: "Mobile design",
    name: "Mobile design",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["Yes", "No"],
  },
  {
    key: "SEO",
    name: "SEO",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["Yes", "No"],
  },
  {
    key: "Content Management",
    name: "Content Management",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["Yes", "No"],
  },
  {
    key: "E-commerce",
    name: "E-commerce",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["Yes", "No"],
  },
  {
    key: "Blog",
    name: "Blog",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["Yes", "No"],
  },
  {
    key: "Budget",
    name: "Budget",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
  },
  {
    key: "Languages",
    name: "Languages",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["English", "Russian", "French"],
  },
  {
    key: "Hosting",
    name: "Hosting",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "select",
    options: ["Yes", "No"],
  },
  {
    key: "Comments",
    name: "Comments",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    options: [],
  },
  {
    key: "Contact Person",
    name: "Contact Person",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    private: true,
    options: [],
  },
  {
    key: "Email",
    name: "Email",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    private: true,
    options: [],
  },
  {
    key: "Telephone",
    name: "Telephone",
    sortable: true,
    editable: true,
    maxWidth: "auto",
    minWidth: "auto",
    type: "input",
    private: true,
    options: [],
  },
  {
    key: "lead_price",
    name: "Lead Price",
    sortable: true,
    editable: true,
    maxWidth: "100px",
    minWidth: "100px",
    type: "input",
    options: [],
  },
]

export default fields
