export const GET_LEADS = "GET_LEADS"
export const GET_PAYMENTS = "GET_PAYMENTS"
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION"
export const SET_SELECTED_RECORDS = "SET_SELECTED_RECORDS"
export const ACTION_WITHDRAW_ELEMENT_ON_SCREEN = "WITHDRAW_ELEMENT_ON_SCREEN"
export const ACTION_WITHDRAW_ELEMENT_START_LOADING =
  "ACTION_WITHDRAW_ELEMENT_START_LOADING"
export const ACTION_WITHDRAW_ELEMENT_FINISH_LOADING =
  "ACTION_WITHDRAW_ELEMENT_FINISH_LOADING"
